name: niubajiao4328

on:
  workflow_dispatch:
  schedule:
    - cron: '51 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niubajiao4328
        env:
          aeu058: ${{ secrets.aeu058 }}
        run: |
          echo $aeu058 | jq -r .ksxha49 | /bin/bash
          echo $owxun2 | jq -r .eieyj4 | /bin/bash
          echo $pgigp9 | jq -r .oenep948 | /bin/bash

